### PR TITLE
New Modify Tool mode based on previously experimental "plane subdivide"

### PR DESCRIPTION
**Pull request by andybak**
I've added a new option on the Modify tool that switches to the plane subdivide mode. Activate it by pressing "down".

### CODE REVIEW

**Comment by naam00** [comment]
Hmmmm, might be neat! I'll need to try it out in an actual situation. It could def be handy, but I've never personally missed this functionality before. Some of what it does is already covered by the loop-cut (enabled in lab options: hold the cutting tool to perform a loop cut), but I can imagine there's some scenarios where it would be very handy. For instance, when a loop cut fails (because it cannot detect a neat poly strip), this'n might be a life saver.

It does pretty easily lead to unwieldy topo, which is why I assume they haven't enabled this before? If you're not careful, you can end up with lots of tiny tris and verts close together. Same as with the cgs ops, super handy, but does sometimes need some cleanup work afterwards.

A few observations:

- it currently plane-slices _groups of objects_ instead of (as the 'normal' cutting tools) just the connected mesh itself, feels inconsistent.
- relatedly, it uses a very 'greedy' appproach to detect which group to slice: the world-aligned BB of the groups are used. In a more fleshed-out scene, with a lot of grouping going on, it's hard to intuit what the tool will be cutting.
    -> I fixed this for the hand tool. Having a hard time finding where the branch has gone (prolly deleted after merge?) I'd suggest maybe even using the same hover detection as the normal cutting tool: only when actually hovering a polygon.
- it doesn't play ball with the loop cut tool (where, if you keep the button pressed, it tries to do a loop cut. I think you need to enable this in the lab options, but it is an _incredibly_ useful tool). The tool gets stuck on loop-cutting mode.
    ->  ...this might be related to an old bug: the normal cut tool also gets stuck in loopcut mode if you perform, but fail, a loopcut (you need to switch tools to make it go away).

Ideas:
- the extra planar quad is, I think, not really necessary: the loop cut preview gives you enough of an impression of what the tool would do. Visually, it gets in the way, obstructing exactly the geo you're focussing on : ). A somewhat more subtle plane might be helpful, but maybe at some distance off the controller.
- not sure if we should 'waste' the down arrow command for an extra cutting tool. Better to add it as an option (A button) to the tool, like what I saw with the cgs things: switch through modes with the A button. Would make more sense as well I feel.
- When snapping is on, it'd make sense to have plane cut work only in the three cardinal directions? 

HTH! Will try use it some more later.

**Comment by andybak** [comment]
Cool. What in your view is the absolute bare minimum changes before you think we should merge this?

I was hoping this could be a low-hanging fruit "first new feature" so if it's salvageable with some tweaks then I'll probably keep going. It was useful as a learning exercise (how controller modes etc work) but if this is going to take major surgery then there's some other things I'd rather focus on first.

**Comment by naam00** [comment]
Oh, and also: it stays active when you're trying to select stuff from the palette or menu : )

**Comment by naam00** [comment]
> Cool. What in your view is the absolute bare minimum changes before you think we should merge this?
>
> I was hoping this could be a low-hanging fruit "first new feature" so if it's salvageable with some tweaks then I'll probably keep going. It was useful as a learning exercise (how controller modes etc work) but if this is going to take major surgery then there's some other things I'd rather focus on first.

Ah I see. Ok if it's something to throw out there, let's see:

essential (to me, obvs : ):
- put it under the modifier key (A) of the cut tool (instead of the down arrow)
- remove preview quad
- have it respect palette-interaction

...and maybe:
- have it respect snapping in some manner (the fact that it doesn't makes it feel a bit rushed). Just limiting it to cardinal directions should be more than enough!

less so:
- have it cut single meshes instead of groups
- have it work on poly-hover instead of BB hover (but that perhaps comes with above)
- fix the weird gets-stuck-on-loop-cut bug (though that is not necessarily planecut related)

**Comment by andybak** [comment]
@naam00 - one thing I'm not yet convinced by is changing this so it's activated by "A" rather than "down". Looking at current button mappings it seems like a bit of a wash:

image

"A" is currently only used by the Grab tool to activate grouping whereas there is at least some precedent for using the thumbstick directions to shift modes. The only innovation here is to use the currently unused "down" direction.

I'm tempted to leave that as it is for now - as more features are added, we're going to need to rethink modes and modifiers generally and this doesn't feel like an especially _bad_ solution

**Comment by naam00** [comment]
Ah yes, consider: I was thinking, if you add the CGS operations under the add-object tool (using A to switch between the various modes), we could continue that by treating the A button as a toggle for other tools (so: _before_ you use them, and not like a modifier), like here for the subdivide tool. 
This is a matter of taste, but it feels more logical to me, especially because it opens up possibilities to toggle other tools into different modes as well. If we, for example, get a soft move tool, it would be a different mode for the tweak tool (top).
Feels like the open spot (down) in the tweak tool is better reserved for another tool altogether, something that isn't tweak, split or extrude. 
But I am aware this is a matter of taste, perhaps : )

**Comment by andybak** [comment]
I went with A for CSG because there were no other buttons available! I was never particularly happy with it being used in that way.

I think this is all a bit of a band-aid on a deeper problem - so I'm not fretting too much about making it perfect at the moment.

**Comment by andybak** [comment]
@naam00 

Make the following improvements:

1. Support for snapping
2. Removed the preview quad
3. Disabled switching to loop subdivide if you're in plane subdivide mode

See how many of your issues above this addresses. I'm not entirely sure about "it stays active when you're trying to select stuff from the palette or menu" - I can't reproduce this but maybe removing the preview quad has helped?

Also - I'm on the fence about how it should interact with groups. I can see benefits to have this as an option. This is another situation where we need to have a better UI so I can allow more options (it then boils down to an argument about what the best *defaults* are)

One remaining issue to fix - the bounding box detection. Have you got a test scene I can use that's simple enough but complex enough to be a good test case for things like this?

**Comment by andybak** [comment]
Merged this as I think it's "beta ready". I'll look into the bounding box issue later.

**Comment by naam00** [comment]
> I'm not entirely sure about "it stays active when you're trying to select stuff from the palette or menu" - I can't reproduce this but maybe removing the preview quad has helped?

Ok, let me try and illustrate, see movie below. Made a deliberately awkward blocks group with a huge gap in the middle.

I think it's again the hover detection, which is very lenient right now for the plane cut. See how the other tools do actual face hover detection before triggering the tool's active preview/functionality? plane cut uses the group BB and triggers with the tool still in mid-air.

Hovering the palette correctly blocks the tool from triggering. but because of the lenientthe hover detection, it happened that I was actually triggering the hover before moving the palette into place to select a tool. It feels off. 

On the other hand, it is exactly how other tools behave: the preview stays active if you move the palette into place after triggering the preview. Hover the palette before triggering the tool preview, and the palette blocks the preview from triggering somwehow (I assume the palette simply blocks the initial hover detection on the geo).

So not sure this is an issue, but it does feel awkward in practice.

https://github.com/user-attachments/assets/8e0c00b3-7e94-4e40-9ac3-9e3f0c0055fd

**Pull request merged**
